# SPDX-FileCopyrightText: Copyright Corsinvest Srl
# SPDX-License-Identifier: MIT

<#
.SYNOPSIS
Repository tasks: analyze, update the manifest, generate the cmdlet reference, run the tests.

.DESCRIPTION
Works from any folder: paths are relative to this script. No task imports the module into your session.

- Analyze:        PSScriptAnalyzer on the module (needs the PSScriptAnalyzer module).
- UpdateManifest: FunctionsToExport and AliasesToExport of the manifest, read from the .psm1 with the
                  PowerShell parser: the public functions (Verb-Pve*) and every Set-Alias. Run it after
                  the generator updates the module or after adding a function.
- Reference:      pages of the cmdlet reference of the documentation site (docs/), also run by npm.
- Test:           offline tests of the hand-written functions (tests/Test-GuestSelection.ps1, tests/Test-RestApi.ps1).

Without -Task: Analyze and Test.

To try the module of the repository: Import-Module ./Corsinvest.ProxmoxVE.Api -Force
The tests against a real cluster are separate, they create and remove guests: tests/Invoke-ClusterTest.ps1

.EXAMPLE
./build.ps1 -Task UpdateManifest
#>
[CmdletBinding()]
param(
    [ValidateSet('Analyze', 'UpdateManifest', 'Reference', 'Test')]
    [string[]]$Task = @('Analyze', 'Test')
)

$ErrorActionPreference = 'Stop'
$moduleDir = Join-Path $PSScriptRoot 'Corsinvest.ProxmoxVE.Api'
$manifestPath = Join-Path $moduleDir 'Corsinvest.ProxmoxVE.Api.psd1'
$rootModulePath = Join-Path $moduleDir 'Corsinvest.ProxmoxVE.Api.psm1'

function Invoke-Analyze {
    if (-not (Get-Module -ListAvailable PSScriptAnalyzer)) {
        throw 'PSScriptAnalyzer is not installed: Install-Module PSScriptAnalyzer -Scope CurrentUser'
    }
    Import-Module PSScriptAnalyzer
    # PSUseSingularNouns: the names follow the API paths (Get-PveNodes).
    # PSAvoidGlobalVars: $Global:PveTicketLast is the documented last connection, used by every cmdlet.
    $results = Invoke-ScriptAnalyzer -Path $rootModulePath -ExcludeRule PSUseSingularNouns, PSAvoidGlobalVars

    # The generated cmdlets (after the marker) are fixed in the generator, not here: count them per rule
    # and show the details of the hand-written part only.
    $marker = (Select-String -Path $rootModulePath -Pattern '## API AUTOGENERATED ##' | Select-Object -First 1).LineNumber
    $handWritten = @($results | Where-Object Line -lt $marker)
    $generated = @($results | Where-Object Line -ge $marker)

    Write-Host "Hand-written part: $($handWritten.Count) findings"
    $handWritten | Sort-Object Line | Format-Table Line, Severity, RuleName, Message -AutoSize -Wrap | Out-Host

    Write-Host "Generated part: $($generated.Count) findings (fixed in cv4pve-api-pwsh-generator)"
    $generated | Group-Object Severity, RuleName | Sort-Object Count -Descending | Format-Table Count, Name -AutoSize | Out-Host

    $errors = @($results | Where-Object Severity -eq 'Error')
    if ($errors.Count) { throw "PSScriptAnalyzer: $($errors.Count) errors" }
}

function Invoke-UpdateManifest {
    $errors = $null
    $ast = [System.Management.Automation.Language.Parser]::ParseFile($rootModulePath, [ref]$null, [ref]$errors)
    if ($errors.Count -gt 0) { throw "Parse errors in ${rootModulePath}: $($errors[0].Message)" }

    # Only the public functions, Verb-Pve*: internal helpers (Test-PortQuick, Get-TaskStatusData, ...)
    # have no 'Pve' in the noun and stay private.
    $functions = $ast.FindAll({ param($n) $n -is [System.Management.Automation.Language.FunctionDefinitionAst] }, $false) |
        ForEach-Object Name | Where-Object { $_ -match '^[A-Za-z]+-Pve' } | Sort-Object -Unique

    $aliases = $ast.FindAll({ param($n) $n -is [System.Management.Automation.Language.CommandAst] -and $n.GetCommandName() -eq 'Set-Alias' }, $false) |
        ForEach-Object {
            $e = $_.CommandElements
            for ($i = 1; $i -lt $e.Count - 1; $i++) {
                if ($e[$i] -is [System.Management.Automation.Language.CommandParameterAst] -and $e[$i].ParameterName -eq 'Name') { $e[$i + 1].Value }
            }
        } | Sort-Object -Unique

    # Update-ModuleManifest writes the comments of the manifest in the UI language: keep them English
    $uiCulture = [System.Threading.Thread]::CurrentThread.CurrentUICulture
    try {
        [System.Threading.Thread]::CurrentThread.CurrentUICulture = 'en-US'
        Update-ModuleManifest -Path $manifestPath -FunctionsToExport $functions -AliasesToExport $aliases
    }
    finally {
        [System.Threading.Thread]::CurrentThread.CurrentUICulture = $uiCulture
    }
    Write-Host "Manifest: $(@($functions).Count) functions, $(@($aliases).Count) aliases"
}

function Invoke-Reference {
    & (Join-Path $PSScriptRoot 'docs/scripts/Update-CmdletReference.ps1')
}

function Invoke-Test {
    # in a child process: the tests import the module and replace some of its functions with fakes
    foreach ($test in 'Test-GuestSelection.ps1', 'Test-RestApi.ps1') {
        & (Get-Process -Id $PID).Path -NoProfile -File (Join-Path $PSScriptRoot "tests/$test")
        if ($LASTEXITCODE -ne 0) { throw "Tests failed: $test (exit code $LASTEXITCODE)" }
    }
}

foreach ($name in $Task) {
    Write-Host "== $name" -ForegroundColor Cyan
    & "Invoke-$name"
}
