# SPDX-FileCopyrightText: Copyright Corsinvest Srl
# SPDX-License-Identifier: MIT

<#
.SYNOPSIS
Generates the cmdlet reference of the documentation site from the module source.

.DESCRIPTION
Reads Corsinvest.ProxmoxVE.Api.psm1 with the PowerShell parser (the module is not imported, so its
classes need no `using module`) and writes one Markdown page per exported function under
docs/src/content/docs/reference/, grouped like the Proxmox VE API, plus an index page per group and
src/data/cmdlets.json (cmdlet name -> page, used by the redirects of the old site).

The pages are not committed: npm runs this script before `dev` and `build` (`predev`, `prebuild`),
locally and in the docs workflow, so the reference always matches the module. Everything under
reference/ is overwritten.

.EXAMPLE
pwsh -NoProfile -File docs/scripts/Update-CmdletReference.ps1
#>
[CmdletBinding()]
param()

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$root = Resolve-Path (Join-Path $PSScriptRoot '../..')
$moduleDir = Join-Path $root 'Corsinvest.ProxmoxVE.Api'
$psm1 = Join-Path $moduleDir 'Corsinvest.ProxmoxVE.Api.psm1'
$psd1 = Join-Path $moduleDir 'Corsinvest.ProxmoxVE.Api.psd1'
$docsDir = Join-Path $root 'docs'
$outDir = Join-Path $docsDir 'src/content/docs/reference'
$dataFile = Join-Path $docsDir 'src/data/cmdlets.json'

$base = '/cv4pve-api-powershell'
$apiViewer = 'https://pve.proxmox.com/pve-docs/api-viewer/#'
$generatedMarker = '## API AUTOGENERATED ##'

# Internal helpers that the old site documented: their old pages redirect to the module functions.
$internal = @('Test-PortQuick', 'VmCheckIdOrName', 'IsNumeric')

# Hand-written functions: the guide page that explains them.
$guides = [ordered]@{
    'Connect-PveCluster'                 = 'connection/'
    'Invoke-PveRestApi'                  = 'concepts/raw-api/'
    'ConvertFrom-PveUnixTime'            = 'concepts/results/#dates'
    'ConvertTo-PveUnixTime'              = 'concepts/results/#dates'
    'Wait-PveTaskIsFinish'               = 'concepts/tasks/'
    'Wait-PveTaskIsFinishedWithProgress' = 'concepts/tasks/'
    'Get-PveTaskIsRunning'               = 'concepts/tasks/'
    'Get-PveGuest'                          = 'guides/finding-vms/'
    'Get-PveNode'                        = 'guides/finding-vms/'
    'Start-PveGuest'                        = 'guides/power/'
    'Stop-PveGuest'                         = 'guides/power/'
    'Suspend-PveGuest'                      = 'guides/power/'
    'Resume-PveGuest'                       = 'guides/power/'
    'Reset-PveGuest'                        = 'guides/power/'
    'Unlock-PveGuest'                       = 'guides/power/'
    'Restart-PveGuest'                      = 'guides/power/'
    'Get-PveTaskExitStatus'                 = 'concepts/tasks/'
    'Get-PveGuestSnapshot'                  = 'guides/snapshots/'
    'New-PveGuestSnapshot'                  = 'guides/snapshots/'
    'Remove-PveGuestSnapshot'               = 'guides/snapshots/'
    'Undo-PveGuestSnapshot'                 = 'guides/snapshots/'
    'Invoke-PveSpice'                    = 'guides/spice/'
}

# Invoke-PveRestApi -Method value -> HTTP method.
$httpMethods = @{ Get = 'GET'; Set = 'PUT'; Create = 'POST'; Delete = 'DELETE' }

# A group of the API with fewer cmdlets than this goes into the "general" page of its parent.
$minGroupSize = 3

#region helpers
function Write-Utf8File([string]$Path, [string[]]$Lines) {
    $dir = Split-Path $Path -Parent
    if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
    [IO.File]::WriteAllText($Path, (($Lines -join "`n").TrimEnd() + "`n"), [Text.UTF8Encoding]::new($false))
}

# The generator writes ':' as "':'" and '[' as '\[' in the comment-based help; undo it.
function Get-CleanText([string]$Text) {
    if ([string]::IsNullOrWhiteSpace($Text)) { return '' }
    $t = $Text.Replace("':'", ':').Replace('\[', '[')
    $t = ($t -split "`r?`n" | ForEach-Object { $_.Trim() }) -join ' '
    $t = $t -replace ' {2,}', ' '
    if ($t.Trim() -eq '--') { return '' }
    return $t.Trim()
}

# Plain Markdown: HTML special characters as entities, so '<GUEST>' is shown and not taken as a tag.
function ConvertTo-MdText([string]$Text) {
    return $Text.Replace('&', '&amp;').Replace('<', '&lt;').Replace('>', '&gt;')
}

function ConvertTo-MdCell([string]$Text) {
    return (ConvertTo-MdText $Text).Replace('|', '\|')
}

function ConvertTo-YamlString([string]$Text) {
    return "'" + $Text.Replace("'", "''") + "'"
}

function Get-FirstSentence([string]$Text) {
    if (-not $Text) { return '' }
    $m = [regex]::Match($Text, '^(.+?\.)(\s|$)')
    $s = $m.Success ? $m.Groups[1].Value : $Text
    return $s.Length -gt 160 ? $s.Substring(0, 157).TrimEnd() + '...' : $s
}

function Get-HelpText($Dictionary, [string]$Key) {
    if ($null -eq $Dictionary) { return '' }
    foreach ($k in $Dictionary.Keys) { if ($k -ieq $Key) { return $Dictionary[$k] } }
    return ''
}

function Get-Slug([string]$Name) { return $Name.ToLowerInvariant() }

# Comment-based help of a function: the first <# … #> block in its text. Parsed here because
# FunctionDefinitionAst.GetHelpContent() takes about 250 ms per function on this file.
function Get-CommentHelp([string]$FunctionText) {
    $help = @{ Synopsis = ''; Description = ''; Outputs = ''; Parameters = @{}; Examples = [System.Collections.Generic.List[string]]::new() }
    $m = [regex]::Match($FunctionText, '<#(.*?)#>', 'Singleline')
    if (-not $m.Success) { return $help }
    $section = $null; $arg = $null; $buffer = [System.Collections.Generic.List[string]]::new()
    $flush = {
        $text = ($buffer -join "`n").Trim()
        switch ($section) {
            'SYNOPSIS' { $help.Synopsis = $text }
            'DESCRIPTION' { $help.Description = $text }
            'OUTPUTS' { $help.Outputs = $text }
            'PARAMETER' { $help.Parameters[$arg] = $text }
            'EXAMPLE' { $help.Examples.Add($text) }
        }
        $buffer.Clear()
    }
    foreach ($line in ($m.Groups[1].Value -split "`r?`n")) {
        $k = [regex]::Match($line, '^\s*\.([A-Za-z]+)\s*(\S*)\s*$')
        if ($k.Success) {
            & $flush
            $section = $k.Groups[1].Value.ToUpperInvariant(); $arg = $k.Groups[2].Value
        }
        else { $buffer.Add($line) }
    }
    & $flush
    return $help
}

function Format-CodeList([string[]]$Items) { return ($Items | ForEach-Object { '`' + $_ + '`' }) -join ', ' }

# '$FabricId' -> '{fabric_id}': the generator title-cases the API name and drops '_' and '-', so an
# inner capital marks a separator: '_' for every path parameter of the current module (checked
# against the Proxmox VE apidoc.js).
# The generator leaves API names with '-' unreplaced, as literal placeholders with '_'
# ("/cluster/sdn/route-maps/entries/{route_map_id}"): shown here with the API's own name.
$literalPlaceholders = @{ '{route_map_id}' = '{route-map-id}'; '{pci_id_or_mapping}' = '{pci-id-or-mapping}' }
function ConvertTo-ApiPath([string]$Resource) {
    $path = [regex]::Replace($Resource, '\$([A-Za-z0-9_]+)', {
            param($m)
            $n = $m.Groups[1].Value.TrimEnd('_')
            '{' + ([regex]::Replace($n, '(?<=[a-z0-9])([A-Z])', '_$1')).ToLowerInvariant() + '}'
        })
    foreach ($k in $literalPlaceholders.Keys) { $path = $path.Replace($k, $literalPlaceholders[$k]) }
    return $path
}
#endregion

#region parse
$tokens = $null
$errors = $null
$ast = [System.Management.Automation.Language.Parser]::ParseFile($psm1, [ref]$tokens, [ref]$errors)
if ($errors.Count -gt 0) { throw "Parse errors in ${psm1}: $($errors[0].Message)" }

$markerLine = (Select-String -Path $psm1 -Pattern ([regex]::Escape($generatedMarker)) | Select-Object -First 1).LineNumber
if (-not $markerLine) { throw "Marker '$generatedMarker' not found in $psm1" }

$exported = (Import-PowerShellDataFile $psd1).FunctionsToExport

# Aliases: Set-Alias -Name X -Value Y
$aliases = @{}
$ast.FindAll({ param($n) $n -is [System.Management.Automation.Language.CommandAst] -and $n.GetCommandName() -eq 'Set-Alias' }, $false) |
    ForEach-Object {
        $e = $_.CommandElements
        $name = $null; $value = $null
        for ($i = 1; $i -lt $e.Count - 1; $i++) {
            if ($e[$i] -is [System.Management.Automation.Language.CommandParameterAst]) {
                if ($e[$i].ParameterName -eq 'Name') { $name = $e[$i + 1].Value }
                elseif ($e[$i].ParameterName -eq 'Value') { $value = $e[$i + 1].Value }
            }
        }
        if ($name -and $value) {
            if (-not $aliases.ContainsKey($value)) { $aliases[$value] = [System.Collections.Generic.SortedSet[string]]::new() }
            [void]$aliases[$value].Add($name)
        }
    }

$functions = $ast.FindAll({ param($n) $n -is [System.Management.Automation.Language.FunctionDefinitionAst] }, $false) |
    Where-Object { $exported -contains $_.Name -and $internal -notcontains $_.Name }

$cmdlets = foreach ($fn in $functions) {
    $help = Get-CommentHelp $fn.Extent.Text
    $handWritten = $fn.Extent.StartLineNumber -lt $markerLine

    $parameters = foreach ($p in $fn.Body.ParamBlock.Parameters) {
        $name = $p.Name.VariablePath.UserPath
        $type = ($p.Attributes | Where-Object { $_ -is [System.Management.Automation.Language.TypeConstraintAst] } |
            Select-Object -First 1).TypeName.Name
        $paramAttr = $p.Attributes | Where-Object {
            $_ -is [System.Management.Automation.Language.AttributeAst] -and $_.TypeName.Name -eq 'Parameter'
        } | Select-Object -First 1
        $named = @($paramAttr ? $paramAttr.NamedArguments : @())
        $validateSet = $p.Attributes | Where-Object {
            $_ -is [System.Management.Automation.Language.AttributeAst] -and $_.TypeName.Name -eq 'ValidateSet'
        } | Select-Object -First 1

        $description = Get-CleanText (Get-HelpText $help.Parameters $name)
        # The generator appends the allowed values; they are shown from ValidateSet instead.
        $description = ($description -replace '\s*Enum: \S+$', '').Trim()

        [pscustomobject]@{
            Name         = $name
            Type         = $type ?? 'object'
            Mandatory    = [bool]($named | Where-Object ArgumentName -eq 'Mandatory')
            Pipeline     = [bool]($named | Where-Object ArgumentName -eq 'ValueFromPipeline')
            ByProperty   = [bool]($named | Where-Object ArgumentName -eq 'ValueFromPipelineByPropertyName')
            Values       = @($validateSet ? ($validateSet.PositionalArguments | ForEach-Object { $_.Value } | Where-Object { $_ -ne '' }) : @())
            Default      = $p.DefaultValue ? $p.DefaultValue.Extent.Text : ''
            Description  = $description
        }
    }

    $method = $null; $path = $null
    if (-not $handWritten) {
        $call = $fn.Body.Find({ param($n) $n -is [System.Management.Automation.Language.CommandAst] -and $n.GetCommandName() -eq 'Invoke-PveRestApi' }, $true)
        $e = $call.CommandElements
        for ($i = 1; $i -lt $e.Count - 1; $i++) {
            if ($e[$i] -is [System.Management.Automation.Language.CommandParameterAst]) {
                if ($e[$i].ParameterName -eq 'Method') { $method = $httpMethods[$e[$i + 1].Value] }
                elseif ($e[$i].ParameterName -eq 'Resource') { $path = ConvertTo-ApiPath $e[$i + 1].Value }
            }
        }
        if (-not $method -or -not $path) { throw "No Invoke-PveRestApi call found in $($fn.Name)" }
    }

    [pscustomobject]@{
        Name        = $fn.Name
        HandWritten = $handWritten
        Description = Get-CleanText ($help.Description ? $help.Description : $help.Synopsis)
        Outputs     = Get-CleanText (@($help.Outputs) -join ' ')
        Examples    = @($help.Examples)
        Parameters  = @($parameters)
        Method      = $method
        Path        = $path
        Aliases     = @($aliases.ContainsKey($fn.Name) ? $aliases[$fn.Name] : @())
        Group       = $null
    }
}
#endregion

#region groups
# Group like the API: first path segment; cluster and nodes one level deeper
# (/cluster/<group>/…, /nodes/{node}/<group>/…).
foreach ($c in $cmdlets) {
    if ($c.HandWritten) { $c.Group = 'module'; continue }
    $seg = @($c.Path.Trim('/').Split('/'))
    $c.Group = switch ($seg[0]) {
        'cluster' { $seg.Count -ge 2 ? "cluster/$($seg[1])" : 'cluster/general' }
        'nodes' { $seg.Count -ge 3 ? "nodes/$($seg[2])" : 'nodes/general' }
        default { $seg[0] }
    }
}
foreach ($parent in 'cluster', 'nodes') {
    $cmdlets | Where-Object { $_.Group -like "$parent/*" } | Group-Object Group |
        Where-Object Count -lt $minGroupSize | ForEach-Object { $_.Group | ForEach-Object { $_.Group = "$parent/general" } }
}

$groupInfo = [ordered]@{
    'module'  = 'Functions written by hand in the module: connection, raw API, tasks, VMs by id or name, snapshots.'
    'access'  = '/access — users, groups, roles, ACL, realms, API tokens, two-factor authentication.'
    'cluster' = '/cluster — cluster-wide configuration: SDN, firewall, notifications, HA, mappings, ACME, backup jobs, replication.'
    'nodes'   = '/nodes — everything on a node: VMs (qemu), containers (lxc), Ceph, storage, disks, network, services, tasks.'
    'pools'   = '/pools — resource pools.'
    'storage' = '/storage — storage definitions of the datacenter.'
    'version' = '/version — Proxmox VE version.'
}
$unknown = $cmdlets.Group | ForEach-Object { $_.Split('/')[0] } | Sort-Object -Unique | Where-Object { -not $groupInfo.Contains($_) }
if ($unknown) { throw "Top-level API groups without a description: $($unknown -join ', ')" }
#endregion

#region write
function Get-Url($c) { "$base/reference/$($c.Group)/$(Get-Slug $c.Name)/" }

function Get-Syntax($c) {
    $parts = foreach ($p in $c.Parameters) {
        $arg = $p.Type -eq 'switch' ? "-$($p.Name)" : "-$($p.Name) <$($p.Type)>"
        $p.Mandatory ? $arg : "[$arg]"
    }
    # One parameter per line: readable without scrolling sideways.
    return (@($c.Name) + ($parts + '[<CommonParameters>]' | ForEach-Object { "    $_" })) -join "`n"
}

if (Test-Path $outDir) { Remove-Item $outDir -Recurse -Force }

foreach ($c in $cmdlets) {
    $lines = [System.Collections.Generic.List[string]]::new()
    $summary = Get-FirstSentence $c.Description
    $lines.Add('---')
    $lines.Add("title: $($c.Name)")
    $lines.Add("description: $(ConvertTo-YamlString ($summary ? $summary : "$($c.Name) cmdlet of Corsinvest.ProxmoxVE.Api."))")
    $lines.Add('editUrl: false')
    $lines.Add('---')
    $lines.Add('')
    $lines.Add('<!-- Generated by docs/scripts/Update-CmdletReference.ps1 from the module source: do not edit. -->')
    $lines.Add('')
    if ($c.Description) { $lines.Add((ConvertTo-MdText $c.Description)); $lines.Add('') }

    if ($c.Path) {
        $lines.Add("**API:** ``$($c.Method) $($c.Path)`` — [Proxmox VE API viewer]($apiViewer$($c.Path))")
        $lines.Add('')
    }
    elseif ($guides.Contains($c.Name)) {
        $lines.Add("Explained with examples in [this guide]($base/$($guides[$c.Name])).")
        $lines.Add('')
    }
    if ($c.Aliases.Count) {
        $lines.Add("**Aliases:** $(Format-CodeList $c.Aliases)")
        $lines.Add('')
    }

    $lines.Add('## Syntax')
    $lines.Add('')
    $lines.Add('```powershell')
    $lines.Add((Get-Syntax $c))
    $lines.Add('```')
    $lines.Add('')

    if ($c.Parameters.Count) {
        $lines.Add('## Parameters')
        $lines.Add('')
        if ($c.HandWritten) {
            $lines.Add('| Parameter | Type | Required | Pipeline | Description |')
            $lines.Add('|---|---|---|---|---|')
        }
        else {
            $lines.Add('| Parameter | Type | Required | Description |')
            $lines.Add('|---|---|---|---|')
        }
        foreach ($p in $c.Parameters) {
            $desc = ConvertTo-MdCell $p.Description
            if ($desc -and $desc -notmatch '[.!?:)]$') { $desc += '.' }
            if ($p.Values.Count) { $desc = ($desc ? "$desc " : '') + "Values: $(Format-CodeList $p.Values)." }
            if ($p.Default -and $p.Type -ne 'switch') { $desc = ($desc ? "$desc " : '') + "Default: ``$($p.Default)``." }
            $row = "| ``-$($p.Name)`` | ``$($p.Type)`` | $($p.Mandatory ? 'Yes' : 'No') |"
            if ($c.HandWritten) {
                $pipe = $p.Pipeline ? 'By value, by property name' : ($p.ByProperty ? 'By property name' : 'No')
                $row += " $pipe |"
            }
            $lines.Add("$row $desc |")
        }
        $lines.Add('')
        if (-not $c.HandWritten) {
            $lines.Add("Every parameter also binds by property name from the pipeline, so an object with ``node`` and ``vmid`` properties — the output of [Get-PveGuest]($base/reference/module/get-pveguest/), for one — fills ``-Node`` and ``-Vmid``. Without ``-PveTicket`` the cmdlet uses the last connection, see [Connection]($base/connection/#the-last-connection).")
            $lines.Add('')
        }
    }

    $lines.Add('## Output')
    $lines.Add('')
    if ($c.HandWritten) {
        $lines.Add($c.Outputs ? (ConvertTo-MdText $c.Outputs) : 'Not documented in the module.')
    }
    else {
        $lines.Add("A ``PveResponse``: the data returned by Proxmox VE is in ``.Response.data``, the outcome in ``.IsSuccessStatusCode`` — see [Results]($base/concepts/results/) and [Errors]($base/concepts/errors/).")
    }
    $lines.Add('')

    if ($c.HandWritten -and $c.Examples.Count) {
        $lines.Add('## Example')
        $lines.Add('')
        foreach ($ex in $c.Examples) {
            $lines.Add('```powershell')
            $lines.Add(($ex.Trim() -replace "`r", ''))
            $lines.Add('```')
            $lines.Add('')
        }
    }

    Write-Utf8File (Join-Path $outDir "$($c.Group)/$(Get-Slug $c.Name).md") $lines
}

# One index per group folder, with the table of its cmdlets.
$folders = $cmdlets.Group | ForEach-Object {
    $_
    if ($_ -like '*/*') { $_.Split('/')[0] }
} | Sort-Object -Unique

foreach ($folder in $folders) {
    $inFolder = @($cmdlets | Where-Object { $_.Group -eq $folder -or $_.Group -like "$folder/*" } | Sort-Object Name)
    $top = $folder.Split('/')[0]
    $isTop = $folder -notlike '*/*'
    $title = $folder -eq 'module' ? 'Module functions' : ($isTop ? "/$folder" : "/$top/…/$($folder.Split('/')[1])")
    $desc = $isTop ? $groupInfo[$top] : "Cmdlets for $(($inFolder | Select-Object -First 1).Path -replace '^(/nodes/\{node\}|/cluster)/([^/]+).*$', '$1/$2') and below."
    if ($folder -like '*/general') { $desc = "Cmdlets of /$top that do not belong to a larger group." }

    $lines = [System.Collections.Generic.List[string]]::new()
    $lines.Add('---')
    $lines.Add("title: $(ConvertTo-YamlString $title)")
    $lines.Add("description: $(ConvertTo-YamlString "$desc ($($inFolder.Count) cmdlets)")")
    $lines.Add('editUrl: false')
    $lines.Add('sidebar:')
    $lines.Add('  label: Overview')
    $lines.Add('  order: 0')
    $lines.Add('---')
    $lines.Add('')
    $lines.Add('<!-- Generated by docs/scripts/Update-CmdletReference.ps1 from the module source: do not edit. -->')
    $lines.Add('')
    $lines.Add("$(ConvertTo-MdText $desc) $($inFolder.Count) cmdlets.")
    $lines.Add('')
    if ($folder -eq 'module') {
        $lines.Add('| Cmdlet | Description |')
        $lines.Add('|---|---|')
        foreach ($c in $inFolder) { $lines.Add("| [$($c.Name)]($(Get-Url $c)) | $(ConvertTo-MdCell (Get-FirstSentence $c.Description)) |") }
    }
    else {
        # A list, not a table: endpoints and cmdlet names are long and would not fit side by side.
        foreach ($c in ($inFolder | Sort-Object Path, Method)) {
            $desc = Get-FirstSentence $c.Description
            $lines.Add("- [$($c.Name)]($(Get-Url $c)) — ``$($c.Method) $($c.Path)``$($desc ? '<br>' + (ConvertTo-MdText $desc) : '')")
        }
    }
    Write-Utf8File (Join-Path $outDir "$folder/index.md") $lines
}

# Reference home: the groups and the aliases.
$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add('---')
$lines.Add('title: Cmdlet reference')
$lines.Add("description: 'Every cmdlet of Corsinvest.ProxmoxVE.Api, grouped like the Proxmox VE API, with its endpoint and parameters.'")
$lines.Add('editUrl: false')
$lines.Add('sidebar:')
$lines.Add('  label: Overview')
$lines.Add('  order: 0')
$lines.Add('---')
$lines.Add('')
$lines.Add('<!-- Generated by docs/scripts/Update-CmdletReference.ps1 from the module source: do not edit. -->')
$lines.Add('')
$version = (Import-PowerShellDataFile $psd1).ModuleVersion
$lines.Add("$($cmdlets.Count) cmdlets of module version ${version}: $(@($cmdlets | Where-Object HandWritten).Count) written by hand, $(@($cmdlets | Where-Object { -not $_.HandWritten }).Count) generated from the Proxmox VE API — one per endpoint and method. How a cmdlet name maps to its endpoint is explained in [Raw API]($base/concepts/raw-api/#from-endpoint-to-cmdlet).")
$lines.Add('')
$lines.Add('| Group | Cmdlets | Contents |')
$lines.Add('|---|---|---|')
foreach ($g in $groupInfo.Keys) {
    $n = @($cmdlets | Where-Object { $_.Group -eq $g -or $_.Group -like "$g/*" }).Count
    $label = $g -eq 'module' ? 'Module functions' : "/$g"
    $lines.Add("| [$label]($base/reference/$g/) | $n | $(ConvertTo-MdCell $groupInfo[$g]) |")
}
$lines.Add('')
$lines.Add('## Aliases')
$lines.Add('')
$lines.Add('Shorter names for common cmdlets, defined by the module.')
$lines.Add('')
$lines.Add('| Alias | Cmdlet |')
$lines.Add('|---|---|')
$byName = @{}; $cmdlets | ForEach-Object { $byName[$_.Name] = $_ }
foreach ($target in ($aliases.Keys | Sort-Object)) {
    foreach ($a in $aliases[$target]) {
        $link = $byName.ContainsKey($target) ? "[$target]($(Get-Url $byName[$target]))" : "``$target``"
        $lines.Add("| ``$a`` | $link |")
    }
}
Write-Utf8File (Join-Path $outDir 'index.md') $lines

# cmdlet -> page, for the redirects of the old MkDocs pages (markdown/<Cmdlet>.html).
$map = [ordered]@{}
$cmdlets | Sort-Object Name | ForEach-Object { $map[$_.Name] = "reference/$($_.Group)/$(Get-Slug $_.Name)/" }
# Old pages of names that are now aliases (Get-PveVm -> Get-PveGuest): the page of the function.
foreach ($target in $aliases.Keys) {
    $page = $map[$target]
    if ($page) { foreach ($a in $aliases[$target]) { if (-not $map.Contains($a)) { $map[$a] = $page } } }
}
# The old site also had pages for the internal helpers: send them to the module functions.
$internal | ForEach-Object { if (-not $map.Contains($_)) { $map[$_] = 'reference/module/' } }
Write-Utf8File $dataFile @(($map | ConvertTo-Json))

Write-Host "Written $($cmdlets.Count) cmdlet pages and $($folders.Count + 1) index pages to $outDir"
#endregion
